/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 t_shirt.glb -T --shadows
Author: Garry Smiths (https://sketchfab.com/garrysithr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-0c2da077451f46c789ebd023cebd6c4e
Title: T Shirt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../utils/angle'

export default function Tshirt() {
  const { nodes, materials } = useGLTF('/models/tShirt/t_shirt-transformed.glb')
  return (
    <group  
    dispose={null} 
    scale={2.5} 
    castShadow
    position={[-1,-1.5,-1]}
    rotation={[angleToRadians(0), angleToRadians(0), 0]}>
      <group scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0_1.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_2949190_Knit_Fleece_Terry_FRONT_109192_0_2.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['30_Knit_Fleece_Terry_FRONT_109192_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['31_Knit_Fleece_Terry_FRONT_109192_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['64_Knit_Fleece_Terry_FRONT_109192_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['70_Knit_Fleece_Terry_FRONT_109192_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['71_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['28_Knit_Fleece_Terry_FRONT_109192_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_1'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes['29_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_2'].geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_1.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4474558_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_2.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_1.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.Pattern2D_4491756_Knit_Fleece_Terry_Copy_1_FRONT_109203_0_2.geometry} material={materials.Knit_Fleece_Terry_FRONT_109192} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_127574_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_127574_Material109415_0_1.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_128590_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_128590_Material109415_0_1.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_129132_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_130377_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_130377_Material109415_0_1.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_130648_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_130909_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_132157_Material109415_0.geometry} material={materials.Material109415} />
        <mesh castShadow receiveShadow geometry={nodes.StitchMatShape_132157_Material109415_0_1.geometry} material={materials.Material109415} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tShirt/t_shirt-transformed.glb')
